# 18-447 RISC-V 32-bit Simulator Makefile
#
# ECE 18-447
# Carnegie Mellon University
#
# This Makefile compiles the simulator and assembles test into RISC-V code for
# the simulator.
#
# Authors:
# 	- 2016: Brandon Perez

################################################################################
#                           DO NOT MODIFY THIS FILE!                           #
#                  You should only add files or change sim.c!                  #
################################################################################

################################################################################
# Configuration
################################################################################

# The compiler for the simulator, along with its flags
SIM_CC = gcc
SIM_CFLAGS = -Wall -Wextra -std=gnu99 -pedantic -g

# The directory for the simulator source file, and all of the files for it
SIM_SRC_DIR = src
SIM = $(shell find $(SIM_SRC_DIR) -type f -name '*.c' -o -name '*.h')

# The name of the exeuctable generated by compiling the simulator
SIM_EXECUTABLE = riscv-sim

################################################################################
# Targets
################################################################################

# The clean target doesn't correspond to an actual file
.PHONY: clean

# Compile the simulator into an executable
$(SIM_EXECUTABLE): $(SIM)
	$(SIM_CC) $(SIM_CFLAGS) $(filter %.c,$^) -o $@

# Cleanup any intermediate files
clean:
	rm -f $(SIM_EXECUTABLE)
